services:
  web:
    build: .
    container_name: ticket_purchase_web
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env
  db:
    image: postgres:16
    container_name: ticket_purchase_db
    restart: always
    environment:
      POSTGRES_USER: ivan
      POSTGRES_PASSWORD: ivanpass
      POSTGRES_DB: ticket_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  postgres_data: